services:
  mysqldb:
    image: mysql:8
    restart: always
    build:
      context: ./mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: Admin1234!
      MYSQL_DATABASE: video
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldb/sql/init.sql:/docker-entrypoint-initdb.d/init.sql