web_list = '''https://apnews.com/
https://www.reuters.com/
https://www.afp.com/en
https://www.bbc.com/news
https://www.nbcnews.com/
https://abcnews.go.com/
https://www.cbsnews.com/
https://www.cnn.com/
https://www.aljazeera.com/
https://www.foxnews.com/
https://www.bloomberg.com/
https://www.washingtonpost.com/
https://www.nytimes.com/
https://www.theguardian.com/international
https://www.wsj.com/
https://www3.nhk.or.jp/news/
https://www.dw.com/en/
https://www.rtve.es/noticias/
https://www.abc.net.au/news/
https://www.ft.com/
https://www.latimes.com/
https://www.chicagotribune.com/
https://www.bostonglobe.com/
https://english.chosun.com/
https://www.tokyo-np.co.jp/
https://www.faz.net/
https://timesofindia.indiatimes.com/
https://www.telegraph.co.uk/
https://www.scmp.com/
https://www.smh.com.au/
https://www.straitstimes.com/
https://www.asahi.com/ajw/
https://www.economist.com/
https://www.nationalgeographic.com/
https://cn.reuters.com/
https://asia.nikkei.com/
https://time.com/
https://www.newsweek.com/
https://www.spiegel.de/international/
https://www.lemonde.fr/en/
https://www.hindustantimes.com/
https://economictimes.indiatimes.com/
https://www.zaobao.com.sg/
https://www.globaltimes.cn/
https://www.france24.com/en/
https://www.zdf.de/international/
https://www.cbc.ca/news/
https://www.nzherald.co.nz/
https://en.prothomalo.com/
https://www.zaobao.com.sg/
https://www.channelnewsasia.com/
https://www.bangkokpost.com/
https://www.thestar.com.my/
https://english.chosun.com/
https://www.tokyo-np.co.jp/
https://www.faz.net/
https://timesofindia.indiatimes.com/
https://www.telegraph.co.uk/
https://www.scmp.com/
https://www.smh.com.au/
https://www.straitstimes.com/
https://www.asahi.com/ajw/
https://www.economist.com/
https://www.nationalgeographic.com/
https://cn.reuters.com/
https://asia.nikkei.com/
https://time.com/
https://www.newsweek.com/
https://www.spiegel.de/international/
https://www.lemonde.fr/en/
https://www.hindustantimes.com/'''